export const TcpData = {
  proxies: [
    {
      name: '1810.frp.web',
      conf: {
        name: '1810.frp.web',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6632,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 7522,
      todayTrafficOut: 651,
      curConns: 0,
      lastStartTime: '08-05 10:31:40',
      lastCloseTime: '08-05 10:31:06',
      status: 'online',
    },
    {
      name: '1810.uclient',
      conf: {
        name: '1810.uclient',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6633,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 345597,
      todayTrafficOut: 17061134,
      curConns: 3,
      lastStartTime: '08-05 10:31:40',
      lastCloseTime: '08-05 10:31:06',
      status: 'online',
    },
    {
      name: '1810.xg3.ssh',
      conf: {
        name: '1810.xg3.ssh',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6631,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 39218800,
      todayTrafficOut: 602928,
      curConns: 1,
      lastStartTime: '08-05 10:31:40',
      lastCloseTime: '08-05 10:31:06',
      status: 'online',
    },
    {
      name: '1810.xg3.web',
      conf: {
        name: '1810.xg3.web',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6630,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 225610,
      todayTrafficOut: 4155773,
      curConns: 0,
      lastStartTime: '08-05 10:31:40',
      lastCloseTime: '08-05 10:31:06',
      status: 'online',
    },
    {
      name: '1810.xiaomi.pc',
      conf: {
        name: '1810.xiaomi.pc',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6634,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 0,
      todayTrafficOut: 0,
      curConns: 0,
      lastStartTime: '08-05 10:31:40',
      lastCloseTime: '08-05 10:31:06',
      status: 'online',
    },
    {
      name: 'clife.7000',
      conf: {
        name: 'clife.7000',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6615,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 276898,
      todayTrafficOut: 3078238,
      curConns: 0,
      lastStartTime: '08-05 12:21:42',
      lastCloseTime: '08-05 12:21:26',
      status: 'online',
    },
    {
      name: 'clife.fnos.ssh',
      conf: {
        name: 'clife.fnos.ssh',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6613,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 0,
      todayTrafficOut: 0,
      curConns: 0,
      lastStartTime: '08-05 12:21:42',
      lastCloseTime: '08-05 12:21:26',
      status: 'online',
    },
    {
      name: 'clife.fnos.web',
      conf: {
        name: 'clife.fnos.web',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6614,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 0,
      todayTrafficOut: 0,
      curConns: 0,
      lastStartTime: '08-05 12:21:42',
      lastCloseTime: '08-05 12:21:26',
      status: 'online',
    },
    {
      name: 'clife.m4.ssh',
      conf: {
        name: 'clife.m4.ssh',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6612,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 0,
      todayTrafficOut: 0,
      curConns: 0,
      lastStartTime: '08-05 12:21:42',
      lastCloseTime: '08-05 12:21:26',
      status: 'online',
    },
    {
      name: 'clife.xg3.ssh',
      conf: {
        name: 'clife.xg3.ssh',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6611,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 12930070,
      todayTrafficOut: 1042250,
      curConns: 0,
      lastStartTime: '08-05 12:21:42',
      lastCloseTime: '08-05 12:21:26',
      status: 'online',
    },
    {
      name: 'clife.xg3.web',
      conf: {
        name: 'clife.xg3.web',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6610,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 723927,
      todayTrafficOut: 5407251,
      curConns: 0,
      lastStartTime: '08-05 12:21:42',
      lastCloseTime: '08-05 12:21:26',
      status: 'online',
    },
    {
      name: 'fnos.clink-frps',
      conf: {
        name: 'fnos.clink-frps',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6111,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 0,
      todayTrafficOut: 0,
      curConns: 0,
      lastStartTime: '08-03 04:25:53',
      lastCloseTime: '',
      status: 'online',
    },
    {
      name: 'fnos.frpc.admin',
      conf: {
        name: 'fnos.frpc.admin',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6105,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 1977,
      todayTrafficOut: 528,
      curConns: 0,
      lastStartTime: '08-03 04:25:53',
      lastCloseTime: '',
      status: 'online',
    },
    {
      name: 'fnos.m4.ssh',
      conf: {
        name: 'fnos.m4.ssh',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6106,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 22852068,
      todayTrafficOut: 32255809,
      curConns: 4,
      lastStartTime: '08-03 04:25:53',
      lastCloseTime: '',
      status: 'online',
    },
    {
      name: 'fnos.m4.vnc',
      conf: {
        name: 'fnos.m4.vnc',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6107,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 0,
      todayTrafficOut: 0,
      curConns: 0,
      lastStartTime: '08-03 04:25:53',
      lastCloseTime: '',
      status: 'online',
    },
    {
      name: 'fnos.nas',
      conf: {
        name: 'fnos.nas',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6100,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 47,
      todayTrafficOut: 295,
      curConns: 0,
      lastStartTime: '08-03 04:25:53',
      lastCloseTime: '',
      status: 'online',
    },
    {
      name: 'fnos.opewrt',
      conf: {
        name: 'fnos.opewrt',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6108,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 0,
      todayTrafficOut: 0,
      curConns: 0,
      lastStartTime: '08-03 04:25:53',
      lastCloseTime: '',
      status: 'online',
    },
    {
      name: 'fnos.ssh',
      conf: {
        name: 'fnos.ssh',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6101,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 3262136,
      todayTrafficOut: 4462652,
      curConns: 0,
      lastStartTime: '08-03 04:25:53',
      lastCloseTime: '',
      status: 'online',
    },
    {
      name: 'fnos.sshtool',
      conf: {
        name: 'fnos.sshtool',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6103,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 2460,
      todayTrafficOut: 1776,
      curConns: 0,
      lastStartTime: '08-03 04:25:53',
      lastCloseTime: '',
      status: 'online',
    },
    {
      name: 'fnos.teamide',
      conf: {
        name: 'fnos.teamide',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6104,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 0,
      todayTrafficOut: 0,
      curConns: 0,
      lastStartTime: '08-03 04:25:53',
      lastCloseTime: '',
      status: 'online',
    },
    {
      name: 'fnos.uclient',
      conf: {
        name: 'fnos.uclient',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6112,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 0,
      todayTrafficOut: 0,
      curConns: 0,
      lastStartTime: '08-03 04:25:53',
      lastCloseTime: '',
      status: 'online',
    },
    {
      name: 'fnos.wrt.ssh',
      conf: {
        name: 'fnos.wrt.ssh',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6113,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 0,
      todayTrafficOut: 0,
      curConns: 0,
      lastStartTime: '08-03 04:25:53',
      lastCloseTime: '',
      status: 'online',
    },
    {
      name: 'fnos.xunlei',
      conf: {
        name: 'fnos.xunlei',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6102,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 0,
      todayTrafficOut: 0,
      curConns: 0,
      lastStartTime: '08-03 04:25:53',
      lastCloseTime: '',
      status: 'online',
    },
    {
      name: 'fnos.老黎',
      conf: {
        name: 'fnos.老黎',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6109,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 0,
      todayTrafficOut: 0,
      curConns: 0,
      lastStartTime: '08-03 04:25:53',
      lastCloseTime: '',
      status: 'online',
    },
    {
      name: 'fnos.运维',
      conf: {
        name: 'fnos.运维',
        type: 'tcp',
        transport: {
          bandwidthLimit: '',
          bandwidthLimitMode: 'client',
        },
        loadBalancer: {
          group: '',
        },
        healthCheck: {
          type: '',
          intervalSeconds: 0,
        },
        localIP: '127.0.0.1',
        plugin: null,
        remotePort: 6110,
      },
      clientVersion: '0.62.1',
      todayTrafficIn: 0,
      todayTrafficOut: 0,
      curConns: 0,
      lastStartTime: '08-03 04:25:53',
      lastCloseTime: '',
      status: 'online',
    },
  ],
}
