run-name: "清空Release ${{ github.ref_name }}"
on:
  push:
    tags:
      - 'v[0-99]*.[0-99]*.[0-99]*'  # 匹配所有以 v 开头的标签（如 v1.0.0）
jobs:
  delete-release:
    runs-on: ubuntu-latest
    steps:
      - name: Delete All Releases
        uses: emmanuel-oliveira/github-releases@v1
        with:
          mode: "delete"
          githubToken: ${{ secrets.GH_TOKEN }}
          itemsToKeep: 0  # 设为0表示删除全部Release